# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install build dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        libffi-dev \
        python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy source code
COPY . /app

# Install Python package
RUN pip install --no-cache-dir .

# Default command
CMD ["alibaba-cloud-ops-mcp-server", "--transport", "stdio"]
